/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellCashSessionRouteImport } from './routes/_shell.cash-session'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellKdsRouteImport } from './routes/_shell.kds'
import { Route as ShellProfileRouteImport } from './routes/_shell.profile'
import { Route as ShellReservationsRouteImport } from './routes/_shell.reservations'
import { Route as ShellUsersRouteImport } from './routes/_shell.users'
import { Route as ShellExpenseEntriesRouteImport } from './routes/_shell.expense.entries'
import { Route as ShellExpenseHeadsRouteImport } from './routes/_shell.expense.heads'
import { Route as ShellKeyboardBillingIndexRouteImport } from './routes/_shell.keyboard-billing.index'
import { Route as ShellKeyboardBillingOrderIdRouteImport } from './routes/_shell.keyboard-billing.$orderId'
import { Route as ShellMenuAddonsRouteImport } from './routes/_shell.menu.addons'
import { Route as ShellMenuCategoriesRouteImport } from './routes/_shell.menu.categories'
import { Route as ShellMenuItemsRouteImport } from './routes/_shell.menu.items'
import { Route as ShellMenuMenusRouteImport } from './routes/_shell.menu.menus'
import { Route as ShellMenuVariantsRouteImport } from './routes/_shell.menu.variants'
import { Route as ShellOperationsIndexRouteImport } from './routes/_shell.operations.index'
import { Route as ShellOperationsSectionRouteImport } from './routes/_shell.operations.$section'
import { Route as ShellOperationsApprovalMatrixRouteImport } from './routes/_shell.operations.approval-matrix'
import { Route as ShellOperationsDeliveryChargeRouteImport } from './routes/_shell.operations.delivery-charge'
import { Route as ShellOrdersIndexRouteImport } from './routes/_shell.orders.index'
import { Route as ShellOrdersOrderIdRouteImport } from './routes/_shell.orders.$orderId'
import { Route as ShellReportsIndexRouteImport } from './routes/_shell.reports.index'
import { Route as ShellReportsReportIdRouteImport } from './routes/_shell.reports.$reportId'
import { Route as ShellStockIndexRouteImport } from './routes/_shell.stock.index'
import { Route as ShellStockSectionRouteImport } from './routes/_shell.stock.$section'
import { Route as ShellSupportHelpRouteImport } from './routes/_shell.support.help'
import { Route as ShellSupportRaiseTicketRouteImport } from './routes/_shell.support.raise-ticket'
import { Route as ShellSystemIndexRouteImport } from './routes/_shell.system.index'
import { Route as ShellSystemAuditLogRouteImport } from './routes/_shell.system.audit-log'
import { Route as ShellSystemNotificationsRouteImport } from './routes/_shell.system.notifications'
import { Route as ShellTableGridIndexRouteImport } from './routes/_shell.table-grid.index'
import { Route as ShellTablesCategoriesRouteImport } from './routes/_shell.tables.categories'
import { Route as ShellTablesManageRouteImport } from './routes/_shell.tables.manage'
import { Route as ShellTableGridOrderOrderIdRouteImport } from './routes/_shell.table-grid.order.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCashSessionRoute = ShellCashSessionRouteImport.update({
  id: '/cash-session',
  path: '/cash-session',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKdsRoute = ShellKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReservationsRoute = ShellReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpenseEntriesRoute = ShellExpenseEntriesRouteImport.update({
  id: '/expense/entries',
  path: '/expense/entries',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpenseHeadsRoute = ShellExpenseHeadsRouteImport.update({
  id: '/expense/heads',
  path: '/expense/heads',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKeyboardBillingIndexRoute =
  ShellKeyboardBillingIndexRouteImport.update({
    id: '/keyboard-billing/',
    path: '/keyboard-billing/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellKeyboardBillingOrderIdRoute =
  ShellKeyboardBillingOrderIdRouteImport.update({
    id: '/keyboard-billing/$orderId',
    path: '/keyboard-billing/$orderId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellMenuAddonsRoute = ShellMenuAddonsRouteImport.update({
  id: '/menu/addons',
  path: '/menu/addons',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMenuCategoriesRoute = ShellMenuCategoriesRouteImport.update({
  id: '/menu/categories',
  path: '/menu/categories',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMenuItemsRoute = ShellMenuItemsRouteImport.update({
  id: '/menu/items',
  path: '/menu/items',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMenuMenusRoute = ShellMenuMenusRouteImport.update({
  id: '/menu/menus',
  path: '/menu/menus',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMenuVariantsRoute = ShellMenuVariantsRouteImport.update({
  id: '/menu/variants',
  path: '/menu/variants',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperationsIndexRoute = ShellOperationsIndexRouteImport.update({
  id: '/operations/',
  path: '/operations/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperationsSectionRoute = ShellOperationsSectionRouteImport.update({
  id: '/operations/$section',
  path: '/operations/$section',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperationsApprovalMatrixRoute =
  ShellOperationsApprovalMatrixRouteImport.update({
    id: '/operations/approval-matrix',
    path: '/operations/approval-matrix',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOperationsDeliveryChargeRoute =
  ShellOperationsDeliveryChargeRouteImport.update({
    id: '/operations/delivery-charge',
    path: '/operations/delivery-charge',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellOrdersIndexRoute = ShellOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOrdersOrderIdRoute = ShellOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsIndexRoute = ShellReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsReportIdRoute = ShellReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStockIndexRoute = ShellStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStockSectionRoute = ShellStockSectionRouteImport.update({
  id: '/stock/$section',
  path: '/stock/$section',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSupportHelpRoute = ShellSupportHelpRouteImport.update({
  id: '/support/help',
  path: '/support/help',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSupportRaiseTicketRoute = ShellSupportRaiseTicketRouteImport.update({
  id: '/support/raise-ticket',
  path: '/support/raise-ticket',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSystemIndexRoute = ShellSystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSystemAuditLogRoute = ShellSystemAuditLogRouteImport.update({
  id: '/system/audit-log',
  path: '/system/audit-log',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSystemNotificationsRoute =
  ShellSystemNotificationsRouteImport.update({
    id: '/system/notifications',
    path: '/system/notifications',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellTableGridIndexRoute = ShellTableGridIndexRouteImport.update({
  id: '/table-grid/',
  path: '/table-grid/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTablesCategoriesRoute = ShellTablesCategoriesRouteImport.update({
  id: '/tables/categories',
  path: '/tables/categories',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTablesManageRoute = ShellTablesManageRouteImport.update({
  id: '/tables/manage',
  path: '/tables/manage',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTableGridOrderOrderIdRoute =
  ShellTableGridOrderOrderIdRouteImport.update({
    id: '/table-grid/order/$orderId',
    path: '/table-grid/order/$orderId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cash-session': typeof ShellCashSessionRoute
  '/dashboard': typeof ShellDashboardRoute
  '/kds': typeof ShellKdsRoute
  '/profile': typeof ShellProfileRoute
  '/reservations': typeof ShellReservationsRoute
  '/users': typeof ShellUsersRoute
  '/expense/entries': typeof ShellExpenseEntriesRoute
  '/expense/heads': typeof ShellExpenseHeadsRoute
  '/keyboard-billing/$orderId': typeof ShellKeyboardBillingOrderIdRoute
  '/menu/addons': typeof ShellMenuAddonsRoute
  '/menu/categories': typeof ShellMenuCategoriesRoute
  '/menu/items': typeof ShellMenuItemsRoute
  '/menu/menus': typeof ShellMenuMenusRoute
  '/menu/variants': typeof ShellMenuVariantsRoute
  '/operations/$section': typeof ShellOperationsSectionRoute
  '/operations/approval-matrix': typeof ShellOperationsApprovalMatrixRoute
  '/operations/delivery-charge': typeof ShellOperationsDeliveryChargeRoute
  '/orders/$orderId': typeof ShellOrdersOrderIdRoute
  '/reports/$reportId': typeof ShellReportsReportIdRoute
  '/stock/$section': typeof ShellStockSectionRoute
  '/support/help': typeof ShellSupportHelpRoute
  '/support/raise-ticket': typeof ShellSupportRaiseTicketRoute
  '/system/audit-log': typeof ShellSystemAuditLogRoute
  '/system/notifications': typeof ShellSystemNotificationsRoute
  '/tables/categories': typeof ShellTablesCategoriesRoute
  '/tables/manage': typeof ShellTablesManageRoute
  '/keyboard-billing/': typeof ShellKeyboardBillingIndexRoute
  '/operations/': typeof ShellOperationsIndexRoute
  '/orders/': typeof ShellOrdersIndexRoute
  '/reports/': typeof ShellReportsIndexRoute
  '/stock/': typeof ShellStockIndexRoute
  '/system/': typeof ShellSystemIndexRoute
  '/table-grid/': typeof ShellTableGridIndexRoute
  '/table-grid/order/$orderId': typeof ShellTableGridOrderOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cash-session': typeof ShellCashSessionRoute
  '/dashboard': typeof ShellDashboardRoute
  '/kds': typeof ShellKdsRoute
  '/profile': typeof ShellProfileRoute
  '/reservations': typeof ShellReservationsRoute
  '/users': typeof ShellUsersRoute
  '/expense/entries': typeof ShellExpenseEntriesRoute
  '/expense/heads': typeof ShellExpenseHeadsRoute
  '/keyboard-billing/$orderId': typeof ShellKeyboardBillingOrderIdRoute
  '/menu/addons': typeof ShellMenuAddonsRoute
  '/menu/categories': typeof ShellMenuCategoriesRoute
  '/menu/items': typeof ShellMenuItemsRoute
  '/menu/menus': typeof ShellMenuMenusRoute
  '/menu/variants': typeof ShellMenuVariantsRoute
  '/operations/$section': typeof ShellOperationsSectionRoute
  '/operations/approval-matrix': typeof ShellOperationsApprovalMatrixRoute
  '/operations/delivery-charge': typeof ShellOperationsDeliveryChargeRoute
  '/orders/$orderId': typeof ShellOrdersOrderIdRoute
  '/reports/$reportId': typeof ShellReportsReportIdRoute
  '/stock/$section': typeof ShellStockSectionRoute
  '/support/help': typeof ShellSupportHelpRoute
  '/support/raise-ticket': typeof ShellSupportRaiseTicketRoute
  '/system/audit-log': typeof ShellSystemAuditLogRoute
  '/system/notifications': typeof ShellSystemNotificationsRoute
  '/tables/categories': typeof ShellTablesCategoriesRoute
  '/tables/manage': typeof ShellTablesManageRoute
  '/keyboard-billing': typeof ShellKeyboardBillingIndexRoute
  '/operations': typeof ShellOperationsIndexRoute
  '/orders': typeof ShellOrdersIndexRoute
  '/reports': typeof ShellReportsIndexRoute
  '/stock': typeof ShellStockIndexRoute
  '/system': typeof ShellSystemIndexRoute
  '/table-grid': typeof ShellTableGridIndexRoute
  '/table-grid/order/$orderId': typeof ShellTableGridOrderOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/cash-session': typeof ShellCashSessionRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/kds': typeof ShellKdsRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/reservations': typeof ShellReservationsRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/expense/entries': typeof ShellExpenseEntriesRoute
  '/_shell/expense/heads': typeof ShellExpenseHeadsRoute
  '/_shell/keyboard-billing/$orderId': typeof ShellKeyboardBillingOrderIdRoute
  '/_shell/menu/addons': typeof ShellMenuAddonsRoute
  '/_shell/menu/categories': typeof ShellMenuCategoriesRoute
  '/_shell/menu/items': typeof ShellMenuItemsRoute
  '/_shell/menu/menus': typeof ShellMenuMenusRoute
  '/_shell/menu/variants': typeof ShellMenuVariantsRoute
  '/_shell/operations/$section': typeof ShellOperationsSectionRoute
  '/_shell/operations/approval-matrix': typeof ShellOperationsApprovalMatrixRoute
  '/_shell/operations/delivery-charge': typeof ShellOperationsDeliveryChargeRoute
  '/_shell/orders/$orderId': typeof ShellOrdersOrderIdRoute
  '/_shell/reports/$reportId': typeof ShellReportsReportIdRoute
  '/_shell/stock/$section': typeof ShellStockSectionRoute
  '/_shell/support/help': typeof ShellSupportHelpRoute
  '/_shell/support/raise-ticket': typeof ShellSupportRaiseTicketRoute
  '/_shell/system/audit-log': typeof ShellSystemAuditLogRoute
  '/_shell/system/notifications': typeof ShellSystemNotificationsRoute
  '/_shell/tables/categories': typeof ShellTablesCategoriesRoute
  '/_shell/tables/manage': typeof ShellTablesManageRoute
  '/_shell/keyboard-billing/': typeof ShellKeyboardBillingIndexRoute
  '/_shell/operations/': typeof ShellOperationsIndexRoute
  '/_shell/orders/': typeof ShellOrdersIndexRoute
  '/_shell/reports/': typeof ShellReportsIndexRoute
  '/_shell/stock/': typeof ShellStockIndexRoute
  '/_shell/system/': typeof ShellSystemIndexRoute
  '/_shell/table-grid/': typeof ShellTableGridIndexRoute
  '/_shell/table-grid/order/$orderId': typeof ShellTableGridOrderOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cash-session'
    | '/dashboard'
    | '/kds'
    | '/profile'
    | '/reservations'
    | '/users'
    | '/expense/entries'
    | '/expense/heads'
    | '/keyboard-billing/$orderId'
    | '/menu/addons'
    | '/menu/categories'
    | '/menu/items'
    | '/menu/menus'
    | '/menu/variants'
    | '/operations/$section'
    | '/operations/approval-matrix'
    | '/operations/delivery-charge'
    | '/orders/$orderId'
    | '/reports/$reportId'
    | '/stock/$section'
    | '/support/help'
    | '/support/raise-ticket'
    | '/system/audit-log'
    | '/system/notifications'
    | '/tables/categories'
    | '/tables/manage'
    | '/keyboard-billing/'
    | '/operations/'
    | '/orders/'
    | '/reports/'
    | '/stock/'
    | '/system/'
    | '/table-grid/'
    | '/table-grid/order/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cash-session'
    | '/dashboard'
    | '/kds'
    | '/profile'
    | '/reservations'
    | '/users'
    | '/expense/entries'
    | '/expense/heads'
    | '/keyboard-billing/$orderId'
    | '/menu/addons'
    | '/menu/categories'
    | '/menu/items'
    | '/menu/menus'
    | '/menu/variants'
    | '/operations/$section'
    | '/operations/approval-matrix'
    | '/operations/delivery-charge'
    | '/orders/$orderId'
    | '/reports/$reportId'
    | '/stock/$section'
    | '/support/help'
    | '/support/raise-ticket'
    | '/system/audit-log'
    | '/system/notifications'
    | '/tables/categories'
    | '/tables/manage'
    | '/keyboard-billing'
    | '/operations'
    | '/orders'
    | '/reports'
    | '/stock'
    | '/system'
    | '/table-grid'
    | '/table-grid/order/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/cash-session'
    | '/_shell/dashboard'
    | '/_shell/kds'
    | '/_shell/profile'
    | '/_shell/reservations'
    | '/_shell/users'
    | '/_shell/expense/entries'
    | '/_shell/expense/heads'
    | '/_shell/keyboard-billing/$orderId'
    | '/_shell/menu/addons'
    | '/_shell/menu/categories'
    | '/_shell/menu/items'
    | '/_shell/menu/menus'
    | '/_shell/menu/variants'
    | '/_shell/operations/$section'
    | '/_shell/operations/approval-matrix'
    | '/_shell/operations/delivery-charge'
    | '/_shell/orders/$orderId'
    | '/_shell/reports/$reportId'
    | '/_shell/stock/$section'
    | '/_shell/support/help'
    | '/_shell/support/raise-ticket'
    | '/_shell/system/audit-log'
    | '/_shell/system/notifications'
    | '/_shell/tables/categories'
    | '/_shell/tables/manage'
    | '/_shell/keyboard-billing/'
    | '/_shell/operations/'
    | '/_shell/orders/'
    | '/_shell/reports/'
    | '/_shell/stock/'
    | '/_shell/system/'
    | '/_shell/table-grid/'
    | '/_shell/table-grid/order/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/cash-session': {
      id: '/_shell/cash-session'
      path: '/cash-session'
      fullPath: '/cash-session'
      preLoaderRoute: typeof ShellCashSessionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/kds': {
      id: '/_shell/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof ShellKdsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reservations': {
      id: '/_shell/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ShellReservationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expense/entries': {
      id: '/_shell/expense/entries'
      path: '/expense/entries'
      fullPath: '/expense/entries'
      preLoaderRoute: typeof ShellExpenseEntriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expense/heads': {
      id: '/_shell/expense/heads'
      path: '/expense/heads'
      fullPath: '/expense/heads'
      preLoaderRoute: typeof ShellExpenseHeadsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/keyboard-billing/': {
      id: '/_shell/keyboard-billing/'
      path: '/keyboard-billing'
      fullPath: '/keyboard-billing/'
      preLoaderRoute: typeof ShellKeyboardBillingIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/keyboard-billing/$orderId': {
      id: '/_shell/keyboard-billing/$orderId'
      path: '/keyboard-billing/$orderId'
      fullPath: '/keyboard-billing/$orderId'
      preLoaderRoute: typeof ShellKeyboardBillingOrderIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/menu/addons': {
      id: '/_shell/menu/addons'
      path: '/menu/addons'
      fullPath: '/menu/addons'
      preLoaderRoute: typeof ShellMenuAddonsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/menu/categories': {
      id: '/_shell/menu/categories'
      path: '/menu/categories'
      fullPath: '/menu/categories'
      preLoaderRoute: typeof ShellMenuCategoriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/menu/items': {
      id: '/_shell/menu/items'
      path: '/menu/items'
      fullPath: '/menu/items'
      preLoaderRoute: typeof ShellMenuItemsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/menu/menus': {
      id: '/_shell/menu/menus'
      path: '/menu/menus'
      fullPath: '/menu/menus'
      preLoaderRoute: typeof ShellMenuMenusRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/menu/variants': {
      id: '/_shell/menu/variants'
      path: '/menu/variants'
      fullPath: '/menu/variants'
      preLoaderRoute: typeof ShellMenuVariantsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operations/': {
      id: '/_shell/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof ShellOperationsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operations/$section': {
      id: '/_shell/operations/$section'
      path: '/operations/$section'
      fullPath: '/operations/$section'
      preLoaderRoute: typeof ShellOperationsSectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operations/approval-matrix': {
      id: '/_shell/operations/approval-matrix'
      path: '/operations/approval-matrix'
      fullPath: '/operations/approval-matrix'
      preLoaderRoute: typeof ShellOperationsApprovalMatrixRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operations/delivery-charge': {
      id: '/_shell/operations/delivery-charge'
      path: '/operations/delivery-charge'
      fullPath: '/operations/delivery-charge'
      preLoaderRoute: typeof ShellOperationsDeliveryChargeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders/': {
      id: '/_shell/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof ShellOrdersIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/orders/$orderId': {
      id: '/_shell/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof ShellOrdersOrderIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports/': {
      id: '/_shell/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ShellReportsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports/$reportId': {
      id: '/_shell/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ShellReportsReportIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/stock/': {
      id: '/_shell/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof ShellStockIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/stock/$section': {
      id: '/_shell/stock/$section'
      path: '/stock/$section'
      fullPath: '/stock/$section'
      preLoaderRoute: typeof ShellStockSectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/support/help': {
      id: '/_shell/support/help'
      path: '/support/help'
      fullPath: '/support/help'
      preLoaderRoute: typeof ShellSupportHelpRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/support/raise-ticket': {
      id: '/_shell/support/raise-ticket'
      path: '/support/raise-ticket'
      fullPath: '/support/raise-ticket'
      preLoaderRoute: typeof ShellSupportRaiseTicketRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system/': {
      id: '/_shell/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof ShellSystemIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system/audit-log': {
      id: '/_shell/system/audit-log'
      path: '/system/audit-log'
      fullPath: '/system/audit-log'
      preLoaderRoute: typeof ShellSystemAuditLogRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/system/notifications': {
      id: '/_shell/system/notifications'
      path: '/system/notifications'
      fullPath: '/system/notifications'
      preLoaderRoute: typeof ShellSystemNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/table-grid/': {
      id: '/_shell/table-grid/'
      path: '/table-grid'
      fullPath: '/table-grid/'
      preLoaderRoute: typeof ShellTableGridIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tables/categories': {
      id: '/_shell/tables/categories'
      path: '/tables/categories'
      fullPath: '/tables/categories'
      preLoaderRoute: typeof ShellTablesCategoriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/tables/manage': {
      id: '/_shell/tables/manage'
      path: '/tables/manage'
      fullPath: '/tables/manage'
      preLoaderRoute: typeof ShellTablesManageRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/table-grid/order/$orderId': {
      id: '/_shell/table-grid/order/$orderId'
      path: '/table-grid/order/$orderId'
      fullPath: '/table-grid/order/$orderId'
      preLoaderRoute: typeof ShellTableGridOrderOrderIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCashSessionRoute: typeof ShellCashSessionRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellKdsRoute: typeof ShellKdsRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellReservationsRoute: typeof ShellReservationsRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellExpenseEntriesRoute: typeof ShellExpenseEntriesRoute
  ShellExpenseHeadsRoute: typeof ShellExpenseHeadsRoute
  ShellKeyboardBillingOrderIdRoute: typeof ShellKeyboardBillingOrderIdRoute
  ShellMenuAddonsRoute: typeof ShellMenuAddonsRoute
  ShellMenuCategoriesRoute: typeof ShellMenuCategoriesRoute
  ShellMenuItemsRoute: typeof ShellMenuItemsRoute
  ShellMenuMenusRoute: typeof ShellMenuMenusRoute
  ShellMenuVariantsRoute: typeof ShellMenuVariantsRoute
  ShellOperationsSectionRoute: typeof ShellOperationsSectionRoute
  ShellOperationsApprovalMatrixRoute: typeof ShellOperationsApprovalMatrixRoute
  ShellOperationsDeliveryChargeRoute: typeof ShellOperationsDeliveryChargeRoute
  ShellOrdersOrderIdRoute: typeof ShellOrdersOrderIdRoute
  ShellReportsReportIdRoute: typeof ShellReportsReportIdRoute
  ShellStockSectionRoute: typeof ShellStockSectionRoute
  ShellSupportHelpRoute: typeof ShellSupportHelpRoute
  ShellSupportRaiseTicketRoute: typeof ShellSupportRaiseTicketRoute
  ShellSystemAuditLogRoute: typeof ShellSystemAuditLogRoute
  ShellSystemNotificationsRoute: typeof ShellSystemNotificationsRoute
  ShellTablesCategoriesRoute: typeof ShellTablesCategoriesRoute
  ShellTablesManageRoute: typeof ShellTablesManageRoute
  ShellKeyboardBillingIndexRoute: typeof ShellKeyboardBillingIndexRoute
  ShellOperationsIndexRoute: typeof ShellOperationsIndexRoute
  ShellOrdersIndexRoute: typeof ShellOrdersIndexRoute
  ShellReportsIndexRoute: typeof ShellReportsIndexRoute
  ShellStockIndexRoute: typeof ShellStockIndexRoute
  ShellSystemIndexRoute: typeof ShellSystemIndexRoute
  ShellTableGridIndexRoute: typeof ShellTableGridIndexRoute
  ShellTableGridOrderOrderIdRoute: typeof ShellTableGridOrderOrderIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCashSessionRoute: ShellCashSessionRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellKdsRoute: ShellKdsRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellReservationsRoute: ShellReservationsRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellExpenseEntriesRoute: ShellExpenseEntriesRoute,
  ShellExpenseHeadsRoute: ShellExpenseHeadsRoute,
  ShellKeyboardBillingOrderIdRoute: ShellKeyboardBillingOrderIdRoute,
  ShellMenuAddonsRoute: ShellMenuAddonsRoute,
  ShellMenuCategoriesRoute: ShellMenuCategoriesRoute,
  ShellMenuItemsRoute: ShellMenuItemsRoute,
  ShellMenuMenusRoute: ShellMenuMenusRoute,
  ShellMenuVariantsRoute: ShellMenuVariantsRoute,
  ShellOperationsSectionRoute: ShellOperationsSectionRoute,
  ShellOperationsApprovalMatrixRoute: ShellOperationsApprovalMatrixRoute,
  ShellOperationsDeliveryChargeRoute: ShellOperationsDeliveryChargeRoute,
  ShellOrdersOrderIdRoute: ShellOrdersOrderIdRoute,
  ShellReportsReportIdRoute: ShellReportsReportIdRoute,
  ShellStockSectionRoute: ShellStockSectionRoute,
  ShellSupportHelpRoute: ShellSupportHelpRoute,
  ShellSupportRaiseTicketRoute: ShellSupportRaiseTicketRoute,
  ShellSystemAuditLogRoute: ShellSystemAuditLogRoute,
  ShellSystemNotificationsRoute: ShellSystemNotificationsRoute,
  ShellTablesCategoriesRoute: ShellTablesCategoriesRoute,
  ShellTablesManageRoute: ShellTablesManageRoute,
  ShellKeyboardBillingIndexRoute: ShellKeyboardBillingIndexRoute,
  ShellOperationsIndexRoute: ShellOperationsIndexRoute,
  ShellOrdersIndexRoute: ShellOrdersIndexRoute,
  ShellReportsIndexRoute: ShellReportsIndexRoute,
  ShellStockIndexRoute: ShellStockIndexRoute,
  ShellSystemIndexRoute: ShellSystemIndexRoute,
  ShellTableGridIndexRoute: ShellTableGridIndexRoute,
  ShellTableGridOrderOrderIdRoute: ShellTableGridOrderOrderIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
